### ISSUE TITLE
Compatibility with MATLAB2022B

### ISSUE THREAD

**Issue by Jurij97** [alekseikukin/mtbtapi#1]
Is it compatible with 2022B version? I'm getting troubles in terms of string input. It seems that my version of matlab wants as input of several functions (such as webread) just a string, not a string array, which is indeed created. This issue may be solved adjusting every input concatening strings, which may be a long work.

Someone has another solution?

**Comment by alekseikukin** [comment]
Hi!
Can you send some example of problematic code?
I did check of examples.m with MATLAB 2022b, it works without a problem...
